# Método da Eliminação de Gauss com Pivotação Parcial
## Objetivo
O objetivo desse notebook é implementar o método da eliminação de Gauss com Pivotação Parcial.

## Implementação
Nós iremos implementar o algoritmo parte por parte, de acordo com a estratégia mostrada em sala. As instruções estão nos comentários nas funções abaixo. Você só precisa editar onde estiver indicado. 

Para executar uma célula, selecione a célula e pressione ```Ctrl + Enter```. Após implementar as funções abaixo, você deve executar cada uma das células, preferencialmente na ordem em que elas aparecem.


### Função para escolher o pivô

In [31]:
def escolhe_pivo(k, A, b):
    '''Escolhe o pivô de maior valor absoluto na coluna k a partir da linha k 
       da matriz A. Se o pivô estiver numa linha diferente de k, as linhas da
       matriz A e do vetor b são trocadas.
       Saída: booleano (True se houve troca)
    '''
    ## n é a ordem da matriz A
    n = len(A)
    
    ## inicializa flag para controlar se houve troca de linha com false
    houve_troca = False
    ## identifica o elemento de maior valor absoluto e a linha onde ele está
    maior = 0
    linha = k
    for i in range(k, n):
        pivo = A[i][k]
        if abs(pivo) > maior:
            maior = pivo
            linha = i
    
    ## se k for diferente da linha onde está o pivô, troca a linha k 
    ## pela linha do pivô em A e b e atribui o valor True à flag
    if k != linha:
        for i in range(0, n):
            A[k][i], A[linha][i] = A[linha][i], A[k][i]
            b[k], b[linha] = b[linha], b[k]
            
        houve_troca = True
    ## retorna a flag
    return houve_troca
    

Agora precisamos testar se a função está implementada corretamente. Iremos testar com o exemplo mostrado em sala.

In [32]:
A = [[1, 2, 3],
     [3, 1, 0],
     [0, 3, 4]]
b = [3, 4, 3]
## Testaremos com a primeira coluna (k=0)
houveTroca = escolhe_pivo(0, A, b)

print(houveTroca)
print("A =", A)
print("b =", b)

True
A = [[3, 1, 0], [1, 2, 3], [0, 3, 4]]
b = [4, 3, 3]


Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
True
A = [[3, 1, 0], [1, 2, 3], [0, 3, 4]]
b = [4, 3, 3]
```

### Método de Gauss com Pivotação

Copie a função ```substituicoes_retroativas``` que você implementou no notebook gauss.ipynb.


In [33]:
import sys
import numpy as np
from timeit import default_timer as timer

def substituicoes_retroativas(A, b):
    
    A = np.array(np.mat(A),dtype=float)
    b = np.array(np.mat(b),dtype=float)
    
    N = A.shape[0]
    x = np.zeros(N)

    outerLoopRange = range(N-1,-1,-1)


    print("Matriz A:")
    print(A)
    print("\nVetor b:")
    print(b)
    start = timer()

    for i in outerLoopRange:
        partialSum = 0
        innerLoopRange = range(i+1,N)
        for j in innerLoopRange:
            partialSum += A[i,j]*x[j]
        x[i] = (b[0,i] - partialSum)/A[i,i]

  
    end = timer()

    print("\nTempo de execução total aproximado: %e segundos" % (end - start))
    print("Tempo aproximado por iteração: %e segundos" % ((end - start)/N))

    print("\nSolução encontrada:")
    print(x[:,None])

    print("\nVetor de resíduos:")
    print(b - A @ x)

    return x


Agora copie o conteúdo da função ```gauss``` que você implementou no notebook gauss.ipynb, modificando apenas a parte para escolher o pivô. O resto permanece igual.

In [34]:
def gauss_pivot(A, b):
    '''Executa o método da eliminação de Gauss com pivotação para resolver o sistema  linear Ax=b 
    transformando o sistema em um sistema triangular superior equivalente.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n e b é o vetor constante.
    Saída: vetor x
    '''
    ## n é a ordem da matriz A
    n = len(A)
    ## Para cada etapa k
    for k in range(0, n):
        ## Escolhe o pivô
        escolhe_pivo(k, A, b)
        
        ## Para cada linha i
        for i in range(k+1, n):
            ## Calcula o fator m
            m = -A[i][k]/A[k][k]
            ## Atualiza a linha i da matriz, percorrendo todas as colunas j
            for j in range(0, n):
                A[i][j] = A[i][j] + m*A[k][j]
            # Atualiza o vetor b na linha i
            b[i] = b[i] + m*b[k]

            ## Zera o elemento Aik
            A[i][k] = 0
                
    ## Agora resolve o sistema triangular superior usando as substituições 
    ## retroativas
    x = substituicoes_retroativas(A, b)
    return x

**Não se esqueça de executar as células de código acima!**

Agora precisamos testar se a função está implementada corretamente. Também iremos usar o exemplo mostrado em sala.

In [35]:
A = [[1, 2, 3],
     [3, 1, 0],
     [0, 3, 4]]
b = [3, 4, 3]
x = gauss_pivot(A, b)
print(x)

Matriz A:
[[3.         1.         0.        ]
 [0.         3.         4.        ]
 [0.         0.         0.77777778]]

Vetor b:
[[4. 3. 0.]]

Tempo de execução total aproximado: 1.444900e-05 segundos
Tempo aproximado por iteração: 4.816333e-06 segundos

Solução encontrada:
[[1.]
 [1.]
 [0.]]

Vetor de resíduos:
[[0. 0. 0.]]
[1. 1. 0.]


Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
[1.0, 1.0, 0.0]
```
#### Exercício 1
Na célula abaixo, teste o método resolvendo o exercício mostrado em sala:

$\left[\begin{array}{rrr}
1& -3 & 2\\
-2& 8 & -1\\
4& -6 & 5\\
\end{array}\right] \left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right] = \left[\begin{array}{r}
11\\
-15\\
29\\
\end{array}\right] $

In [36]:
## Defina a matriz A e o vetor b e chame a função gauss_pivot
# Escreva o seu código aqui
A = [[1, -3, 3],
     [-2, 8, -1],
     [4, -6, 5]]
b = [11, -15, 29]
x = gauss_pivot(A, b)
print(x)

Matriz A:
[[ 4.  -6.   5. ]
 [ 0.   5.   1.5]
 [ 0.   0.   2.2]]

Vetor b:
[[29.  -0.5  3.6]]

Tempo de execução total aproximado: 1.355600e-05 segundos
Tempo aproximado por iteração: 4.518667e-06 segundos

Solução encontrada:
[[ 4.31818182]
 [-0.59090909]
 [ 1.63636364]]

Vetor de resíduos:
[[0. 0. 0.]]
[ 4.31818182 -0.59090909  1.63636364]


#### Exercício 2
Na célula abaixo, o seguinte sistema linear:

$\left[\begin{array}{rrr}
3& 2 & 4\\
1& 1 & 2\\
4& 3 & -2\\
\end{array}\right] \left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right] = \left[\begin{array}{r}
1\\
2\\
3\\
\end{array}\right] $

In [37]:
## Defina a matriz A e o vetor b e chame a função gauss_pivot
# Escreva o seu código aqui
A = [[3, 2, 4],
     [1, 1, 2],
     [4, 3, -2]]
b = [1, 2, 3]
x = gauss_pivot(A, b)
print(x)

Matriz A:
[[ 4.    3.   -2.  ]
 [ 0.    0.25  2.5 ]
 [ 0.    0.    8.  ]]

Vetor b:
[[3.   1.25 0.  ]]

Tempo de execução total aproximado: 1.492500e-05 segundos
Tempo aproximado por iteração: 4.975000e-06 segundos

Solução encontrada:
[[-3.]
 [ 5.]
 [ 0.]]

Vetor de resíduos:
[[0. 0. 0.]]
[-3.  5.  0.]


### Exercício

Modifique o método de gauss com pivotação para também calcular o determinante.
Use o valor retornado pela função ```escolhe_pivo``` para controlar o número de permutações, P.

$det(A) = (-1)^P \times det(U)$

In [38]:
def gauss_pivot_det(A, b):
    '''Executa o método da eliminação de Gauss com pivotação para resolver o sistema  linear Ax=b 
    transformando o sistema em um sistema triangular superior equivalente.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n e b é o vetor constante.
    Saída: vetor x
    '''
    ## n é a ordem da matriz A
    n = len(A)
    P = 0
    ## Para cada etapa k
    for k in range(0, n):
        ## Escolhe o pivô
        if escolhe_pivo(k, A, b):
            P += 1
        
        ## Para cada linha i
        for i in range(k+1, n):
            ## Calcula o fator m
            m = -A[i][k]/A[k][k]
            ## Atualiza a linha i da matriz, percorrendo todas as colunas j
            for j in range(0, n):
                A[i][j] = A[i][j] + m*A[k][j]
            # Atualiza o vetor b na linha i
            b[i] = b[i] + m*b[k]

            ## Zera o elemento Aik
            A[i][k] = 0
    ## Agora calcula o determinante antes de resolver o sistema triangular superior
    det = 1
    for k in range(0, n):
        det *= A[k][k]
    
    det *= (-1)**P
    # Escreva o seu código aqui
    
    x = substituicoes_retroativas(A, b)
    return (x, det)

Agora teste com o exemplo acima:

$\left[\begin{array}{rrr}
1& -3 & 2\\
-2& 8 & -1\\
4& -6 & 5\\
\end{array}\right] \left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right] = \left[\begin{array}{r}
11\\
-15\\
29\\
\end{array}\right] $

In [39]:
## Defina a matriz A e o vetor b e chame a função gauss_det
# Escreva o seu código aqui
A = [[1, -3, 2],
     [-2, 8, -1],
     [4, -6, 5]]
b = [11, -15, 29]
x = gauss_pivot_det(A, b)
print(x)

Matriz A:
[[ 4.  -6.   5. ]
 [ 0.   5.   1.5]
 [ 0.   0.   1.2]]

Vetor b:
[[29.  -0.5  3.6]]

Tempo de execução total aproximado: 1.317800e-05 segundos
Tempo aproximado por iteração: 4.392667e-06 segundos

Solução encontrada:
[[ 2.]
 [-1.]
 [ 3.]]

Vetor de resíduos:
[[0.0000000e+00 0.0000000e+00 4.4408921e-16]]
(array([ 2., -1.,  3.]), -24.0)


Se tudo deu certo, você deve obter a seguinte resposta:

```[2.0, -1.0, 3.0]  -24.0
```
