# Método da Decomposição LU
## Objetivos
Os objetivos desse notebook são três:

 1. Implementar o método das substituições sucessivas e testá-lo.

 2. Implementar o método da decomposição LU.

 3. Implementar o método que utiliza a decomposição LU para resolver sistemas lineares e testá-lo.

## Implementação
Nós iremos implementar os algoritmos parte por parte, de acordo com as estratégias mostradas em sala. As instruções estão nos comentários nas funções abaixo. Você só precisa editar onde estiver indicado. 

Para executar uma célula, selecione a célula e pressione ```Ctrl + Enter```. Após implementar as funções abaixo, você deve executar cada uma das células, preferencialmente na ordem em que elas aparecem.


### Método das Substituições Sucessivas

In [3]:
import sys
import numpy as np
from timeit import default_timer as timer

def substituicoes_sucessivas(A, b):
    '''Executa o método das substituições sucessivas para resolver o sistema 
       linear triangular inferior Ax=b.
       Parâmetros de entrada: A é uma matriz triangular inferior e b é o vetor constante. 
       Saída: vetor x
    ''' 
    # escreva o código aqui
    A = np.array(np.mat(A),dtype=float)
    b = np.array(np.mat(b),dtype=float)
    
    N = A.shape[0]
    x = np.zeros(N)

    outerLoopRange = range(N)

    print("Matriz A:")
    print(A)
    print("\nVetor b:")
    print(b)
    start = timer()

    for i in outerLoopRange:
        partialSum = 0
        innerLoopRange = range(N-1,-1,-1)
        for j in innerLoopRange:
            partialSum += A[i,j]*x[j]
        x[i] = (b[0,i] - partialSum)/A[i,i]

  
    end = timer()

    print("\nTempo de execução total aproximado: %e segundos" % (end - start))
    print("Tempo aproximado por iteração: %e segundos" % ((end - start)/N))

    print("\nSolução encontrada:")
    print(x[:,None])

    print("\nVetor de resíduos:")
    print(b - A @ x)

    return x
    
    return x

Agora precisamos testar se a função está implementada corretamente. Iremos usar o exemplo mostrado em sala.

In [4]:
A = [[2, 0, 0, 0],
     [3, 5, 0, 0],
     [1, -6, 8, 0],
     [-1, 4, -3, 9]]
b = [4, 1, 48, 6]
x = substituicoes_sucessivas(A, b)
print(x)

Matriz A:
[[ 2.  0.  0.  0.]
 [ 3.  5.  0.  0.]
 [ 1. -6.  8.  0.]
 [-1.  4. -3.  9.]]

Vetor b:
[[ 4.  1. 48.  6.]]

Tempo de execução total aproximado: 2.004100e-05 segundos
Tempo aproximado por iteração: 5.010251e-06 segundos

Solução encontrada:
[[ 2.]
 [-1.]
 [ 5.]
 [ 3.]]

Vetor de resíduos:
[[0. 0. 0. 0.]]
[ 2. -1.  5.  3.]


Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
[2.0, -1.0, 5.0, 3.0]

```

#### Exercício:
Na célula abaixo, resolva o exercício mostrado em sala:

$\begin{cases}
3x_1= 6\\
2x_1 - 3x_2 = 7\\
x_1 + 5x_3 = -8\\
2x_2 + 4x_3 - 3x_4=-3
\end{cases}$

**Não se esqueça de executar as células de código acima!**

In [5]:
## Defina a matriz A e o vetor b e chame a função substituicoes_sucessivas
# Escreva o seu código aqui
A = [[3, 0, 0, 0],
     [2, -3, 0, 0],
     [1, 0, 5, 0],
     [0, 2, 4, -3]]
b = [6, 7, -8, -3]
x = substituicoes_sucessivas(A, b)
print(x)

Matriz A:
[[ 3.  0.  0.  0.]
 [ 2. -3.  0.  0.]
 [ 1.  0.  5.  0.]
 [ 0.  2.  4. -3.]]

Vetor b:
[[ 6.  7. -8. -3.]]

Tempo de execução total aproximado: 3.846900e-05 segundos
Tempo aproximado por iteração: 9.617250e-06 segundos

Solução encontrada:
[[ 2.        ]
 [-1.        ]
 [-2.        ]
 [-2.33333333]]

Vetor de resíduos:
[[0. 0. 0. 0.]]
[ 2.         -1.         -2.         -2.33333333]


### Decomposição LU

Iremos definir uma função que decompõe uma matriz em A no produto de duas matrizes LU.

Para isso, precisaremos da sua função identidade criada no notebook gauss_jordan.ipynb. Copie e cole a sua função na célula abaixo:

In [7]:
from numpy import *
def identidade(n):
    '''Cria uma matriz identidade de ordem n.
    Parâmetros de entrada:  n é a ordem da matriz.
    Saída: matriz identidade de ordem n.
    '''
    # Escreva o seu código aqui
    return identity(n, dtype=float)

**Não se esqueça de executar a célula de código acima!**

A função já foi testada então iremos implementar a função lu. Para isso, é recomendável que você inicie a partir do código usado para a função gauss, pois vimos que a matriz U é a mesma matriz triangular superior gerada pelo método de Gauss. Modifique o método de Gauss, seguindo a estratégia a seguir:

 1. Inicialize a matriz L com a matriz identidade (essa parte já está feita).

 2. Ao calcular o fator m, popule a matriz L na posição correspondente ao fator m calculado.

 3. Remova o código referente à atualização do vetor b, pois não será mais necessário.

 4. Também remova a parte de cálculo do vetor x, pois só será utilizado na função seguinte.

In [10]:
def lu(A):
    '''
    Decompõe a matriz A no produto de duas matrizes L e U. Onde L é uma matriz 
    triangular inferior unitária e U é uma matriz triangular superior.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n.
    Saída: (L,U) tupla com as matrizes L e U
    '''
    n = len(A)
    
    ## Inicializa a matriz L com a matriz identidade
    L = identidade(n)
    
    # Escreva o seu código aqui
    ## n é a ordem da matriz A
    n = len(A)
 
    ## Para cada etapa k
    for k in range(0, n):
        
        ## Para cada linha i
        for i in range(k+1, n):
            
            ## Calcula o fator m
            m = -A[i][k]/A[k][k]
            L[i][k] = m*-1
            
            ## Atualiza a linha i da matriz, percorrendo todas as colunas j
            for j in range(0, n):
                A[i][j] = A[i][j] + m*A[k][j]
 
            ## Zera o elemento Aik
            A[i][k] = 0
    
    return (L, A)

Vamos testar a função com o seguinte exemplo:

In [11]:
def formata_matriz(M):
    m = len(M) # número de linhas
    n = len(M[0]) # número de colunas
    s = ""
    for i in range(m):
        for j in range(n):
           s += "%9.3f " % M[i][j]
        s += "\n"
    return s

A = [[1, -3, 2],
     [-2, 8, -1],
     [4, -6, 5]]
(L, U) = lu(A)
print("L: \n%s" % formata_matriz(L))
print("U: \n%s" % formata_matriz(U))

L: 
    1.000     0.000     0.000 
   -2.000     1.000     0.000 
    4.000     3.000     1.000 

U: 
    1.000    -3.000     2.000 
    0.000     2.000     3.000 
    0.000     0.000   -12.000 



Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
L: 
    1.000     0.000     0.000 
   -2.000     1.000     0.000 
    4.000     3.000     1.000 

U: 
    1.000    -3.000     2.000 
    0.000     2.000     3.000 
    0.000     0.000   -12.000
```

### Resolução de sistema linear usando decomposição LU

Agora vamos implementar a função **resolve_lu(A,b)**.
Antes disso, copie e cole a sua função substituicoes_retroativas implementada no notebook gauss.ipynb.


Implemente a função resolve_lu, seguindo a estratégia a seguir:

 1. Decomponha a matriz A em matrizes L e U usando a função lu.

 2. Resolva o sistema Ly=b.

 3. Resolva o sistema Ux=y.

 4. Retorne x.

In [14]:
import sys
import numpy as np
from timeit import default_timer as timer

def substituicoes_retroativas(A, b):
    
    A = np.array(np.mat(A),dtype=float)
    b = np.array(np.mat(b),dtype=float)
    
    N = A.shape[0]
    x = np.zeros(N)

    outerLoopRange = range(N-1,-1,-1)


    print("Matriz A:")
    print(A)
    print("\nVetor b:")
    print(b)
    start = timer()

    for i in outerLoopRange:
        partialSum = 0
        innerLoopRange = range(i+1,N)
        for j in innerLoopRange:
            partialSum += A[i,j]*x[j]
        x[i] = (b[0,i] - partialSum)/A[i,i]

  
    end = timer()

    print("\nTempo de execução total aproximado: %e segundos" % (end - start))
    print("Tempo aproximado por iteração: %e segundos" % ((end - start)/N))

    print("\nSolução encontrada:")
    print(x[:,None])

    print("\nVetor de resíduos:")
    print(b - A @ x)

    return x


def resolve_lu(A,b):
    '''
    Executa o método LU para resolver o sistema  linear Ax=b.
    Esse método inicialmente decompõe a matriz em L e U e depois resolve os 
    dois sistemas lineares triangulares.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n e b é o vetor constante.
    Saída: vetor x solução do sistema.
    '''
    
    # Escreva o seu código aqui
    (L, U) = lu(A)
    y = substituicoes_sucessivas(L, b)
    x = substituicoes_retroativas(U, y)
    
    return x

Vamos testar a função com o seguinte exemplo:

In [15]:
A = [[1, -3, 2],
     [-2, 8, -1],
     [4, -6, 5]]
b = [11, -15, 29]
x = resolve_lu(A,b)
print(x)

Matriz A:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 4.  3.  1.]]

Vetor b:
[[ 11. -15.  29.]]

Tempo de execução total aproximado: 2.463600e-05 segundos
Tempo aproximado por iteração: 8.212000e-06 segundos

Solução encontrada:
[[ 11.]
 [  7.]
 [-36.]]

Vetor de resíduos:
[[0. 0. 0.]]
Matriz A:
[[  1.  -3.   2.]
 [  0.   2.   3.]
 [  0.   0. -12.]]

Vetor b:
[[ 11.   7. -36.]]

Tempo de execução total aproximado: 1.936300e-05 segundos
Tempo aproximado por iteração: 6.454333e-06 segundos

Solução encontrada:
[[ 2.]
 [-1.]
 [ 3.]]

Vetor de resíduos:
[[0. 0. 0.]]
[ 2. -1.  3.]


Se tudo deu certo, você deve obter a seguinte resposta:

```
[2.0, -1.0, 3.0]

```

## Exercício

Resolva o sistema linear abaixo usando decomposição LU.

$\left[\begin{array}{rrr}
1& 2 & 4\\
2& 0 & 2\\
4& 1 & 3\\
\end{array}\right] \left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right] = \left[\begin{array}{r}
13\\
12\\
25\\
\end{array}\right] $


In [16]:
## Defina a matriz A e chame a função resolve_lu

# Escreva o seu código aqui
A = [[1, 2, 4],
     [2, 0, 2],
     [4, 1, 3]]
b = [13, 12, 25]
x = resolve_lu(A,b)
print(x)

Matriz A:
[[1.   0.   0.  ]
 [2.   1.   0.  ]
 [4.   1.75 1.  ]]

Vetor b:
[[13. 12. 25.]]

Tempo de execução total aproximado: 1.723800e-05 segundos
Tempo aproximado por iteração: 5.746000e-06 segundos

Solução encontrada:
[[ 13. ]
 [-14. ]
 [ -2.5]]

Vetor de resíduos:
[[0. 0. 0.]]
Matriz A:
[[ 1.   2.   4. ]
 [ 0.  -4.  -6. ]
 [ 0.   0.  -2.5]]

Vetor b:
[[ 13.  -14.   -2.5]]

Tempo de execução total aproximado: 1.873000e-05 segundos
Tempo aproximado por iteração: 6.243334e-06 segundos

Solução encontrada:
[[5.]
 [2.]
 [1.]]

Vetor de resíduos:
[[0. 0. 0.]]
[5. 2. 1.]
